#!/bin/bash

# Create an output directory to store genome assembly results generated by Flye
# This directory will contain assembled contigs, assembly graphs, and log files
mkdir flye_out

# Run Flye to perform de novo genome assembly using Oxford Nanopore long-read data
# --nano-raw specifies that the input consists of raw Nanopore reads
# --out-dir defines the output directory for all assembly-related files
# --genome-size provides an estimated genome size for Salmonella enterica (~5 Mb)
# --threads sets the number of CPU threads used during assembly

flye \
--nano-raw SRR32410565.fastq.gz \
--out-dir flye_out \
--genome-size 5m \
--threads 2


