#!/bin/bash

# Align the assembled contigs to the Salmonella enterica reference genome
# using minimap2, which is optimized for long-read and assembly alignments
# -a outputs alignments in SAM format
# -x asm5 applies a preset suitable for aligning assembled contigs
#     with approximately 5% sequence divergence to a reference genome
# The reference genome is provided in FASTA format
# The assembled genome generated by Flye is used as the query
# Alignment results are written to a SAM file for downstream processing

minimap2 -ax asm5 \
GCF_000006945.2_ASM694v2_genomic.fna.gz \
flye_out/assembly.fasta \
> asm_to_ref.sam

